# -*- coding: utf-8 -*-
"""
/***************************************************************************
 urban_type_editor
                                 A QGIS plugin
 This plugin edit and create urban types in the SUEWS database
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-31
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Oskar Bäcklin University of Gothenburg
        email                : oskar.backlin@gu.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QFileDialog, QAction, QMessageBox
from qgis.gui import QgsMapLayerComboBox, QgsFieldComboBox, QgsMessageBar
from qgis.core import QgsVectorLayer, QgsMapLayerProxyModel, Qgis, QgsProject, QgsFieldProxyModel, QgsField
# Initialize Qt resources from file resources.py
from .resources import *
from pathlib import Path
import geopandas as gpd
import webbrowser
import pandas as pd

# Import the code for the dialog
from .urban_type_edior_dialog import urban_type_editorDialog
import os.path


class urban_type_editor:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'urban_type_editor_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Urban Type Editor')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('urban_type_editor', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/urban_type_edior/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

           # Read Database

        
#

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Urban Type Editor'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = urban_type_editorDialog()

        
        db_path = r'C:\Script\NGEO306\database_mkI.xlsx'
        idx_col = 'ID'

        Type = pd.read_excel(db_path, sheet_name= 'Lod1_Types', index_col=  idx_col)
        ref = pd.read_excel(db_path, sheet_name= 'References', index_col= idx_col)
        alb =  pd.read_excel(db_path, sheet_name= 'Lod3_Albedo', index_col= idx_col)
        em =  pd.read_excel(db_path, sheet_name= 'Lod3_Emissivity', index_col= idx_col)
        OHM =  pd.read_excel(db_path, sheet_name= 'Lod3_OHM', index_col= idx_col) # Away from Veg
        LAI =  pd.read_excel(db_path, sheet_name= 'Lod3_LAI', index_col= idx_col)
        st = pd.read_excel(db_path, sheet_name= 'Lod3_Storage', index_col = idx_col)
        cnd = pd.read_excel(db_path, sheet_name= 'Lod3_Conductance', index_col = idx_col) # Away from Veg
        veg = pd.read_excel(db_path, sheet_name= 'Lod2_Veg', index_col = idx_col)
        nonveg = pd.read_excel(db_path, sheet_name= 'Lod2_NonVeg', index_col = idx_col)
        LGP = pd.read_excel(db_path, sheet_name= 'Lod3_LGP', index_col= idx_col)
        dr = pd.read_excel(db_path, sheet_name= 'Lod3_Drainage', index_col= idx_col)
        

        # Clear all ComboBoxes
        comboBoxList = [
            self.dlg.comboBoxRegionIn,
            self.dlg.comboBoxRegionOut]
        
        for i in comboBoxList:
            i.clear()   

        # Add regions from Database to Comboboxes
        self.dlg.comboBoxRegionIn.addItems([*set(Type['Region'])])
        self.dlg.comboBoxRegionIn.setCurrentIndex(-1)

        self.dlg.comboBoxRegionOut.addItems([*set(Type['Region'])])
        self.dlg.comboBoxRegionOut.setCurrentIndex(-1)

        def region_changed(): 
           
            db_path = r'C:\Script\NGEO306\database_mkI.xlsx'
            idx_col = 'ID'
            Type = pd.read_excel(db_path, sheet_name= 'Lod1_Types', index_col=  idx_col)

            reg = self.dlg.comboBoxRegionIn.currentText()
            self.dlg.comboBoxType.clear()
            self.dlg.comboBoxType.addItems(Type['Type'][Type['Region'] == reg])
            self.dlg.comboBoxType.setCurrentIndex(-1)
            self.dlg.comboBoxType.setEnabled(True)


        self.dlg.comboBoxRegionIn.currentIndexChanged.connect(region_changed)
        
        # Update rest of ComboBoxes
        def type_changed(): 
            # Portal thoprugh types  
        
            reg = self.dlg.comboBoxRegionIn.currentText()
            urb_type = self.dlg.comboBoxType.currentText()

            idx = Type.loc[(Type['Region'] == reg) & (Type['Type'] == urb_type)]
            veg_id = idx.reset_index()['ID'].item()
  

            # for i in [self.dlg.comboBoxEvrType, self.dlg.comboBoxDecType, self.dlg.comboBoxGrassType,self.dlg.comboBoxWallMtr,
            #  self.dlg.comboBoxRoofMtr,self.dlg.comboBoxWallClr,self.dlg.comboBoxRoofClr]:
            #     i.clear()
        
            def change_veg(cbox, col, var, idx):
                cbox.clear()
                cbox.addItems((veg[var][veg['Type'] == col].tolist()))
                cbox.setCurrentIndex((veg[var][veg['Type'] == col].tolist()).index(veg.loc[idx[col], var].item()))
            
            def change_nonveg(cbox, col, var, idx):
                cbox.clear()
                cbox.addItems((nonveg[var][nonveg['Type'] == col].tolist()))
                cbox.setCurrentIndex((nonveg[var][nonveg['Type'] == col].tolist()).index(nonveg.loc[idx[col],var].item()))

            change_veg(self.dlg.comboBoxEvrType,'EvrTree', 'Specifics' , idx)
            change_veg(self.dlg.comboBoxDecType,'DecTree', 'Specifics' , idx)
            change_veg(self.dlg.comboBoxGrassType,'Grass', 'Specifics' , idx)
            
            change_nonveg(self.dlg.comboBoxWallMtr, 'Building', 'Material', idx)
            change_nonveg(self.dlg.comboBoxRoofMtr, 'Building', 'Material', idx)
            change_nonveg(self.dlg.comboBoxWallClr, 'Building', 'Color', idx)
            change_nonveg(self.dlg.comboBoxRoofClr, 'Building', 'Color', idx)

            change_nonveg(self.dlg.comboBoxPavedMrt, 'Paved', 'Material', idx)
            change_nonveg(self.dlg.comboBoxPavedClr, 'Paved', 'Color', idx)
        
        self.dlg.comboBoxType.currentIndexChanged.connect(type_changed) 

            
        def typeInfo(self): 
            self.dlg.textEdit.setText(
                'Urban Type Info: '+ self.dlg.newTypeLineEdit +
                '\n\nRegion: ' +  self.dlg.comboBoxRegionOut.currentText())
                # '\n\nPeriod: ' + str(selection['Period'].item()) + 
                # '\n\nDescription: ' + str(selection['Description'].item()) +
                # '\n\nAuthor: ' + str(selection['Author'].item())
             

              # Set up for the Help button
        # self.dlg.infoButton.clicked.connect(self.typeInfo)
            # def change_veg(var, veg_index):
            #     if var == 'Grass':
            #         combobox = self.dlg.comboBoxGrassType
            #         loc1 = 'Grass'
            #     elif var == 'DecTree':
            #         combobox = self.dlg.comboBoxDecType
            #         loc1 = 'Decidous'
            #     elif var == 'EvrTree':
            #         combobox = self.dlg.comboBoxEvrType
            #         loc1 = 'Evergreen'
                

            #     var_list = veg['Specifics'][veg['Type'] == loc1].tolist()
            #     combobox.addItems(var_list)
            #     idx = var_list.index(veg.loc[veg_index[var],'Specifics'].item())
            #     combobox.setCurrentIndex(idx)
                
            # for i in ['Grass', 'DecTree', 'EvrTree']:
            #     change_veg(i, veg_index)

            # self.dlg.comboBoxWallMtr.addItems(nonveg['Material'][nonveg['Type'] == 'Building'].tolist())
            # idx = (nonveg['Material'][nonveg['Type'] == 'Building'].tolist()).index(nonveg.loc[veg_index['Building'],'Material'].item())
            # self.dlg.comboBoxWallMtr.setCurrentIndex(idx)
                
            # self.dlg.comboBoxRoofMtr.addItems(nonveg['Material'][nonveg['Type'] == 'Building'].tolist())
            # idx = (nonveg['Material'][nonveg['Type'] == 'Building'].tolist()).index(nonveg.loc[veg_index['Building'],'Material'].item())
            # self.dlg.comboBoxRoofMtr.setCurrentIndex(idx)

            # self.dlg.comboBoxWallClr.addItems(nonveg['Color'][nonveg['Type'] == 'Building'].tolist())

            # idx = (nonveg['Material'][nonveg['Type'] == 'Building'].tolist().index(nonveg.loc[veg_index['Type'],'Color'].item()))
            # self.dlg.comboBoxWallClr.setCurrentIndex(idx)

#           self.dlg.comboBoxWallClr.setCurrentIndex((var_list.index(nonveg.loc[veg_index['Type'],'Color'].item())))
            
            # self.dlg.comboBoxRoofClr.addItems(nonveg['Color'][nonveg['Type'] == 'Building'].tolist())
            # idx = var_list.index(nonveg.loc[veg_index['Type'],'Material'].item())
            # self.dlg.comboBoxRoofClr.setCurrentIndex(idx)
            
            # self.dlg.comboBoxPavedlMtr.addItems(nonveg['Material'][nonveg['Type'] == 'Paved'].tolist())
            # idx = var_list.index(nonveg.loc[veg_index['Paved'],'Specifics'].item())
            # self.dlg.comboBoxPavedlMtr.setCurrentIndex(idx)
            
#             evrTreeList = veg['Specifics'][veg['Type'] == 'Evergreen'].tolist()
#             self.dlg.comboBoxEvrType.addItems(evrTreeList)
#             idx = evrTreeList.index(veg.loc[veg_index['EvrTree'],'Specifics'].item())
#             self.dlg.comboBoxEvrType.setCurrentIndex(idx)

#             decTreeList = veg['Specifics'][veg['Type'] == 'Decidous'].tolist()
#             self.dlg.comboBoxDecType.addItems(decTreeList)
#             idx = decTreeList.index(veg.loc[veg_index['DecTree'],'Specifics'].item())
#             self.dlg.comboBoxDecType.setCurrentIndex(idx)

#             grassList = veg['Specifics'][veg['Type'] == 'Grass'].tolist()
#             self.dlg.comboBoxGrassType.addItems(grassList)
#             idx = grassList.index(veg.loc[veg_index['Grass'],'Specifics'].item())
#             self.dlg.comboBoxGrassType.setCurrentIndex(idx)
#             #self.dlg.comboBoxDecType.addItems(veg['Specifics'][veg['Type'] == 'Decidous'].tolist())
#             #self.dlg.comboBoxDecType.setCurrentIndex(self.dlg.comboBoxDecType.index(veg.loc[veg_index['Decidous'],'Specifics'].item()))

#             #self.dlg.comboBoxGrassType.addItems(veg['Specifics'][veg['Type'] == 'Grass'].tolist())
#             #self.dlg.comboBoxGrassType.setCurrentIndex(self.dlg.comboBoxGrassType.index(veg.loc[veg_index['Grass'],'Specifics'].item()))

#             # self.dlg.comboBoxEvrType.addItems([*set(veg.loc[Type.loc[:,'EvrTree'], 'Specifics'])])

#             # self.dlg.comboBoxDecType.addItems([*set(veg.loc[Type.loc[:,'DecTree'], 'Specifics'])])

#             # self.dlg.comboBoxGrassType.addItems([*set(veg.loc[Type.loc[:,'Grass'], 'Specifics'])])

# #            self.dlg.comboBoxEvrType.addItems(veg.loc[Type.loc[a,'EvrTree'], 'Specifics'])
#             # self.dlg.comboBoxType.addItems(Type['Type'][Type['Region'] == reg])
#             # self.dlg.comboBoxType.setCurrentIndex(-1)
            # self.dlg.comboBoxType.setEnabled(True)



        

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
